version: "3.9"

services:
  ui:
    restart: always
    image: sb15551/mitch-frontend:latest
    container_name: mitch-fe
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mitch/app/certs:/etc/nginx/certs
      - /mitch/app/conf:/etc/nginx/conf.d
      - /mitch/app/certbot-etc:/etc/letsencrypt
      - /mitch/app/certbot-var:/var/lib/letsencrypt
    networks:
      some_network:
        aliases:
          - frontend.local
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /mitch/app/certbot-etc:/etc/letsencrypt
      - /mitch/app/certbot-var:/var/lib/letsencrypt
      - /mitch/app/web-root:/usr/share/nginx/html
    depends_on:
      - ui
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email stibium128@gmail.com --agree-tos --no-eff-email --force-renewal -d mitch-club.ru
networks:
  some_network:
    name: 'common_network'