version: "3.6"

services:
  ui:
    restart: always
    image: sb15551/mitch-frontend:latest
    container_name: mitch-fe
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mitch/app/certs:/etc/nginx/certs
      - /mitch/app/conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/usr/share/nginx/html
    networks:
      some_network:
        aliases:
          - frontend.local
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/usr/share/nginx/html
    depends_on:
      - ui
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email stibium128@gmail.com --agree-tos --no-eff-email --force-renewal -d mitch-club.ru
volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /mitch/app/web-root/
      o: bind
networks:
  some_network:
    name: 'common_network'