version: "3.9"

services:
  ui:
    restart: always
    image: sb15551/mitch-frontend:latest
    container_name: mitch-fe
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/app/certs:/etc/nginx/certs
      - /root/app/conf:/etc/nginx/conf.d
    networks:
      some_network:
        aliases:
          - frontend.local
networks:
  some_network:
    name: 'common_network'