name: Deployment
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Publish to Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: sb15551/mitch-frontend:latest
          
      - name: Deploy UI service
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: .
          key: ${{secrets.DEPLOY_SERVER_KEY}}
          inventory: |
            [all]
            mitch-club.ru ansible_ssh_port=${{secrets.DEPLOY_SERVER_PORT}} ansible_ssh_user=${{secrets.DEPLOY_SERVER_USERNAME}} ansible_become_user=${{secrets.DEPLOY_SERVER_USERNAME}} ansible_become_password=${{secrets.DEPLOY_SERVER_USERNAME_PASSWORD}}
          options: |
            --verbose
