name: Deployment app
on:
  pull_request:
    branches: [master,main]
    types: closed
env:
  DEPLOY_PATH: /mitch/app/frontend
  BUILD_SCRIPT_OUTPUT: ./docker-compose.yaml
jobs:
  deploy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Publish to Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: sb15551/mitch-frontend:latest
          
      - name: SCP Command to Transfer Files
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1
      
      - name: Run SSH Commands
        uses: arthurvanl/action-exec-ssh@v2.0.7
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_USERNAME_PASSWORD }}
          commands: |
            sudo docker-compose -f /mitch/app/frontend/docker-compose.yaml down
            sudo docker image rm sb15551/mitch-frontend
            sudo docker-compose -f /mitch/app/frontend/docker-compose.yaml up -d
